CREATE TABLE IF NOT EXISTS organizer (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        task TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'undone',
        created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)
